# Generated by Django 4.2.16 on 2024-10-20 04:04

import uuid

from django.db import migrations, models

import cove_ocds.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuppliedData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_url", models.URLField(max_length=2000, null=True)),
                ("original_file", models.FileField(max_length=256, upload_to=cove_ocds.models.upload_to)),
                ("current_app", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified", models.DateTimeField(auto_now=True, null=True)),
                ("rendered", models.BooleanField(default=False)),
                ("schema_version", models.CharField(default="", max_length=10)),
                ("data_schema_version", models.CharField(default="", max_length=10)),
                ("parameters", models.TextField(blank=True, null=True)),
                (
                    "form_name",
                    models.CharField(
                        choices=[
                            ("upload_form", "File upload"),
                            ("url_form", "Downloaded from URL"),
                            ("text_form", "Pasted into textarea"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "input_supplieddata",
            },
        ),
    ]
