# Generated by Django 4.2.16 on 2024-10-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cove_ocds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieddata",
            name="current_app",
            field=models.CharField(default="cove_ocds", max_length=20),
        ),
        migrations.AlterField(
            model_name="supplieddata",
            name="form_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upload_form", "File upload"),
                    ("url_form", "Downloaded from URL"),
                    ("text_form", "Pasted into textarea"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplieddata",
            name="parameters",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplieddata",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=2000),
            preserve_default=False,
        ),
    ]
