# Generated by Django 4.2.16 on 2024-10-20 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cove_ocds", "0002_alter_supplieddata_current_app_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplieddata",
            name="current_app",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="data_schema_version",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="form_name",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="rendered",
        ),
        migrations.RemoveField(
            model_name="supplieddata",
            name="schema_version",
        ),
    ]
