# Generated by Django 4.2.16 on 2024-10-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cove_ocds", "0003_remove_supplieddata_current_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieddata",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
