name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
    secrets:
      personal-access-token: ${{ secrets.PAT }}
    with:
      # https://github.com/OpenDataServices/lib-cove-web/pull/153
      standard-maintenance-scripts-ignore: cove
